/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Travel_Management_System;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author OGUNDIMU SULAIMON
 */
public class Travelling_Management_Systems extends javax.swing.JFrame {

    /**
     * Creates new form Travelling_Management_Systems
     */
    public Travelling_Management_Systems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        postcode = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        standard = new javax.swing.JRadioButton();
        single = new javax.swing.JRadioButton();
        yes2 = new javax.swing.JRadioButton();
        yes1 = new javax.swing.JRadioButton();
        firstclass = new javax.swing.JRadioButton();
        economy = new javax.swing.JRadioButton();
        returnn = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        airporttax = new javax.swing.JRadioButton();
        travellinginsurance = new javax.swing.JRadioButton();
        destination = new javax.swing.JComboBox();
        accommodation = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        subtotal = new javax.swing.JTextField();
        tax = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        receiptB = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipthold = new javax.swing.JTextArea();
        departurepoint = new javax.swing.JComboBox();
        airmilesover20000 = new javax.swing.JRadioButton();
        extluggage = new javax.swing.JRadioButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame2.setForeground(new java.awt.Color(255, 153, 153));
        jFrame2.setIconImages(null);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1370, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 75)); // NOI18N
        jLabel2.setText("Travel Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(91, 91, 91))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Firstname");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Surname");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Post Code");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Telephone");

        firstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        firstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });

        surname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        surname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        postcode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        postcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        telephone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        telephone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Email");

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel19))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(telephone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(surname, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postcode, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstname))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel4, jLabel5, jLabel6, jLabel7});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setText("Flight");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setText("Ticket");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Child");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setText("Adult");

        standard.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        standard.setText("Standard");
        standard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardActionPerformed(evt);
            }
        });

        single.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        single.setText("Single");

        yes2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yes2.setText("Yes");
        yes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes2ActionPerformed(evt);
            }
        });

        yes1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yes1.setText("Yes");
        yes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yes1ActionPerformed(evt);
            }
        });

        firstclass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstclass.setText("First Class");
        firstclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstclassActionPerformed(evt);
            }
        });

        economy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        economy.setText("Economy");

        returnn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        returnn.setText("Return");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(standard)
                    .addComponent(firstclass)
                    .addComponent(economy))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(returnn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(single)
                                .addGap(18, 18, 18)
                                .addComponent(yes1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(52, 52, 52)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(yes2)))))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel8, jLabel9});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {economy, firstclass, returnn, single, standard, yes1, yes2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(standard)
                    .addComponent(single)
                    .addComponent(yes1)
                    .addComponent(yes2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(economy)
                    .addComponent(returnn))
                .addGap(18, 18, 18)
                .addComponent(firstclass)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel8, jLabel9});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {economy, firstclass, returnn, single, standard, yes1, yes2});

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel12.setText("Departure Point");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel13.setText("Destination");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel14.setText("Accommodation");

        airporttax.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        airporttax.setText("Airport Tax");
        airporttax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airporttaxActionPerformed(evt);
            }
        });

        travellinginsurance.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        travellinginsurance.setText("Travelling Insurance");
        travellinginsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travellinginsuranceActionPerformed(evt);
            }
        });

        destination.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        destination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Abuja", "Kebbi", "Kano", "Rivers", "Delta", "Edo", "Enugu", "Imo", "Jigawa" }));

        accommodation.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        accommodation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Single", "Double", "Extra" }));
        accommodation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accommodationActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("Sub Total");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Tax");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setText("Total");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Total");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        subtotal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        tax.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tax, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(subtotal)
                    .addComponent(total))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16, jLabel17});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jLabel15, jLabel16, jLabel17, subtotal, tax, total});

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Receipt");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        receiptB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        receiptB.setText("Receipt");
        receiptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptBActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        receipthold.setColumns(20);
        receipthold.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        receipthold.setRows(5);
        jScrollPane1.setViewportView(receipthold);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(receiptB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptB)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        departurepoint.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        departurepoint.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Lagos", "Ibadan", "Osun", "Ogun", " " }));

        airmilesover20000.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        airmilesover20000.setText("Air Miles over 20000");
        airmilesover20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airmilesover20000ActionPerformed(evt);
            }
        });

        extluggage.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        extluggage.setText("Ext Luggage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(airporttax)
                                    .addComponent(travellinginsurance)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(destination, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(accommodation, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(airmilesover20000, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(extluggage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(departurepoint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departurepoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(accommodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(airporttax)
                            .addComponent(airmilesover20000))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(extluggage)
                            .addComponent(travellinginsurance))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel13});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void standardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_standardActionPerformed

    private void firstclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstclassActionPerformed

    private void yes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yes1ActionPerformed

    private void yes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yes2ActionPerformed

    private void travellinginsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travellinginsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travellinginsuranceActionPerformed
private JFrame frame;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        frame = new JFrame("Exit");
       
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to to exit","Travel management System",JOptionPane.YES_NO_OPTION)
                ==JOptionPane.YES_NO_OPTION)
            { System.exit(0);
            
            }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void accommodationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accommodationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accommodationActionPerformed

    private void airmilesover20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airmilesover20000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airmilesover20000ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        subtotal.setText(null);
        tax.setText(null);
        total.setText(null);
        firstname.setText(null);
        surname.setText(null);
        address.setText(null);
        postcode.setText(null);
        telephone.setText(null);
        email.setText(null);
       departurepoint.setSelectedItem("None");
       destination.setSelectedItem("None");
       accommodation.setSelectedItem("None");
       airporttax.setSelected(false);
       airmilesover20000.setSelected(false);
       travellinginsurance.setSelected(false);
       extluggage.setSelected(false);
       standard.setSelected(false);
       economy.setSelected(false);
       single.setSelected(false);
       returnn.setSelected(false);
       yes1.setSelected(false);
       yes2.setSelected(false);
       firstclass.setSelected(false);

            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    private void taxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        double abuja = 100;
        double kebbi = 105;
        double kano = 110;
        double river = 115;
        double delta = 120;
        double edo = 125;
        double enugu = 130;
        double imo = 135;
        double jigawa = 140;
        
        
        double single = 10;
        double Double = 20;
        double extra = 30; 
        
        double airporttaxx = 5;      
        double Travellinginsurance = 10;    
        double Extluggage = 7.5;    
        double Airmilesover20000 = 8.5; 
        
        double standardd = 15;   
        double economy = 20;   
        double firstclass = 25;   
       
        
        double[] travelcost = new double[20];
        double itax = 2.5;
        
        if((destination.getSelectedItem().equals("Abuja")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = abuja + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Abuja")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = abuja + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Abuja")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = abuja + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Abuja")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = abuja + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Abuja")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = abuja + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
        
        //----------------------------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Kebbi")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = kebbi + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Kebbi")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = kebbi + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Kebbi")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = kebbi + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Kebbi")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = kebbi + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Kebbi")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = kebbi + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
        
        //-----------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Kano")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = kano + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Kano")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = kano + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Kano")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = kano + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Kano")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = kano + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Kano")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = kano + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
        //------------------------------------------------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Rivers")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = river + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Rivers")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = river + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Rivers")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = river + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Rivers")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = river + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Rivers")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = river + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
        //-----------------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Delta")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = delta + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Delta")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = delta + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Delta")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = delta + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Delta")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = delta + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Delta")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = delta + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
         //-----------------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Edo")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = edo + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Edo")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = edo + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Edo")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = edo + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Edo")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = edo + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Edo")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = edo + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
         //-----------------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Enugu")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = enugu + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Enugu")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = enugu + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Enugu")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = enugu + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Enugu")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = enugu + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Enugu")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = enugu + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
         //-----------------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Imo")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = imo + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Imo")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = imo + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Imo")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = imo + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Imo")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = imo + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Imo")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = imo + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
        
        //-----------------------------------------------------------------------------------
        
        if((destination.getSelectedItem().equals("Jigawa")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()))
        {
            travelcost[0] = jigawa + single +standardd;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Jigawa")) &&
                accommodation.getSelectedItem().equals("Single")&& (standard.isSelected()) && airporttax.isSelected())
        {
            travelcost[0] = jigawa + single +standardd +airporttaxx;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Jigawa")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected())
        {
            travelcost[0] = jigawa + single +standardd +airporttaxx + Airmilesover20000;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }   if((destination.getSelectedItem().equals("Jigawa")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected())
        {
            travelcost[0] = jigawa + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }  if((destination.getSelectedItem().equals("Jigawa")) &&
                accommodation.getSelectedItem().equals("Single")&& 
                (standard.isSelected()) && airporttax.isSelected() &&
                airmilesover20000.isSelected() && travellinginsurance.isSelected() && extluggage.isSelected())
        {
            travelcost[0] = jigawa + single +standardd +airporttaxx + Airmilesover20000 + Travellinginsurance + Extluggage;
            travelcost[1] =( (travelcost[0] * itax )/100);
            String Tax  = String.format("$%.2f" , travelcost[1]);
            tax.setText(Tax);
            
            String subtoTal = String.format("$%.2f" , travelcost[0]);
            subtotal.setText(subtoTal);
            
            String Total = String.format("$%.2f" , (travelcost[0] + travelcost[1]));
            total.setText(Total);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void receiptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptBActionPerformed

       Calendar timer = Calendar.getInstance();
       timer.getTime();
       
       SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
       String iTime = tTime.format(timer.getTime());
       
       SimpleDateFormat tDate = new SimpleDateFormat("dd-MMM-yyyy");
       String iDate = tDate.format(timer.getTime());
       
       int num1;
       String ref="";
       num1=1325 + (int) (Math.random()*4238);
       ref += num1 + 1325;
        
       //---------------------------------------------------------------------------------
       
       String Firstname = firstname.getText();
       String Surname = surname.getText();
       String Address = address.getText();
       String Postcode = postcode.getText();
       String Telephone = telephone.getText();
       String Email = email.getText();
       String rTax = tax.getText();
       String Subtotal = subtotal.getText();
       String Total = total.getText();
       
       receipthold.append("\tTravel Management System:\n\n"
               + "Ref:\t\t" +ref
               + "\n--------------------------------------"
               + "\nName:\t\t" + Firstname
               + "\nSurname:\t" + Surname
               + "\nAddress:\t" + Address
               + "\nPostcode:\t" + Postcode
               + "\nTelephone:\t" + Telephone
               + "\nEmail:\t\t" + Email
               + "\nTax:\t\t" + rTax
               + "\nSubTotal:\t" + Subtotal
               + "\nTotal:\t\t" + Total
               + "\n--------------------------------------"
               + "\nDate: " + iDate + " \tTime: " +iTime
               + "\n\n\tThanks For Using Travelling \n\t Management Software"
       );
       
       
    }//GEN-LAST:event_receiptBActionPerformed

    private void airporttaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airporttaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airporttaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travelling_Management_Systems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travelling_Management_Systems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accommodation;
    private javax.swing.JTextField address;
    private javax.swing.JRadioButton airmilesover20000;
    private javax.swing.JRadioButton airporttax;
    private javax.swing.JComboBox departurepoint;
    private javax.swing.JComboBox destination;
    private javax.swing.JRadioButton economy;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton extluggage;
    private javax.swing.JRadioButton firstclass;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField postcode;
    private javax.swing.JButton receiptB;
    private javax.swing.JTextArea receipthold;
    private javax.swing.JRadioButton returnn;
    private javax.swing.JRadioButton single;
    private javax.swing.JRadioButton standard;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField total;
    private javax.swing.JRadioButton travellinginsurance;
    private javax.swing.JRadioButton yes1;
    private javax.swing.JRadioButton yes2;
    // End of variables declaration//GEN-END:variables
}
